### ISSUE TITLE
v8js installation fails

### ISSUE THREAD

**Issue by PhilippSchreiber** [Schreiber-und-Freunde/vagrant-ansible2#1]

**Comment by shakalandy** [comment]
Also, ich hab mir das hier mal angeschaut, da die Box ja aktuell nicht sauber baut.

Zuerstmal musste das Paket "re2c" noch installiert werden, damit überhaupt was geht.
Dann ist die Rolle noch falsch gewesen, da die phplibs von dem php 5.5 Verzeichnis geladen wurden. Das habe ich auch korrigiert.

Der Build geht aber trotzdem nicht, da die v8js libs auch noch gefehlt hatten:

checking for V8 version... 3.14.5.9
configure: error: libv8 must be version 3.24.6 or greater

Die ist dann aber zu alt.
Ach, und die aktuellste pecl version von v8js geht auch nicht, da die PHP 7 braucht. Man muss also die 0.4.1 erzwingen. 

Welche sollte es denn sein? Bitte mal hier schauen:
http://pecl.php.net/package-changelog.php?package=v8js

**Comment by shakalandy** [comment]
haben v8js rausgeschmissen da nicht mehr benötigt.
